name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Placeholder step
        run: echo "This is a placeholder step to avoid workflow errors."

  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Bump version and push tag
        id: bump_version
        uses: phips28/gh-action-bump-version@v9.0.0
        with:
          tag-prefix: ""
          minor-wording: "[_MINOR_]"
          major-wording: "[_MAJOR_]"
          default: "patch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
